"""Per-task linkage between an existing Task Center task and a Runtime run.

AG-G2-AUTO-002-B02.

Where the linkage lives
-----------------------
On the task row's **existing** extras slot. ``task_row_mappers._split_extra``
routes every task-dict key that is not a known ``evoflow_collab_tasks`` column
into that row's existing ``extra_json`` column, and ``_merge_extra`` merges it
back onto the task dict on load. So a single extra key on the task dict is a
safe, persistent, queryable location for this linkage.

Consequences, all intentional:

- no new table, no migration, and no second authoritative task/run state source;
- the linkage travels with the task through the existing save/load path, so it
  survives restarts the same way every other task field does;
- nothing has to be invented: the slot already exists and is already used for
  other extra task fields.

Duplicate-trigger behaviour (the point of this card)
---------------------------------------------------
``link_runtime_run`` never creates a second Runtime Run silently:

- no linkage yet -> attach;
- same attempt (same idempotency key) and the same run -> reuse;
- same attempt but a *different* run -> refuse (the caller must reuse the
  existing run, not create another one);
- a different attempt -> refuse unless ``supersede=True`` is passed explicitly.

Cross-organization reads are refused, not treated as "absent", so a linkage can
never be silently adopted by another organization.

One gate, not one per caller (AG-G2-AUTO-009)
---------------------------------------------
``read_linked_runtime_run`` is the single entry point every Task <-> Runtime path
uses to obtain a linkage, so the trusted-organization and task-ownership checks
exist in exactly one place and cannot drift apart between read, status
projection, cancel, retry/re-attach and event bridging.

Lifecycle hardening (AG-G2-AUTO-010)
------------------------------------
The linkage lives in a client-writable extras slot, so it is never trusted as
input on its own:

- a run id must be non-empty and well-formed, both when it is about to be linked
  and when it is read back out of storage;
- a stored linkage must agree with the trusted context's organization *and* task
  before it is used at all;
- the same attempt can never be rebound to a different run, and a different
  attempt is refused unless a caller passes ``supersede=True`` explicitly
  (no production caller does), so a silent rebinding is impossible.
"""

from __future__ import annotations

import json
import re
from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any, Literal

from app.gateway.task_runtime_context import TaskRuntimeContext

__all__ = [
    "LINKAGE_TASK_KEY",
    "LinkOutcome",
    "RuntimeRunLinkage",
    "RuntimeRunLinkageError",
    "link_runtime_run",
    "read_linked_runtime_run",
    "read_runtime_run_linkage",
    "read_stored_linkage",
]

# The key that lands in the task row's existing extras / extra_json slot.
LINKAGE_TASK_KEY = "runtime_run_linkage"

# A Runtime run id is generated by the Runtime as ``run_<hex>``; the guard stays
# shape-based rather than pinned to that exact form so a Runtime id scheme change
# cannot silently make every stored linkage unreadable. It exists to reject
# empty, whitespace-only, over-long and character-injected values, all of which
# could only come from a tampered extras slot.
_RUN_ID_PATTERN = re.compile(r"[A-Za-z0-9][A-Za-z0-9._:-]{0,127}")

LinkAction = Literal["attached", "reused", "superseded"]


class RuntimeRunLinkageError(RuntimeError):
    """Raised when a runtime run linkage is missing, malformed or unsafe."""


@dataclass(frozen=True)
class RuntimeRunLinkage:
    """A persisted association between one Task Center task and one Runtime run."""

    runtime_run_id: str
    org_scope_key: str
    task_id: str
    idempotency_key: str

    def to_dict(self) -> dict[str, str]:
        return {
            "runtime_run_id": self.runtime_run_id,
            "org_scope_key": self.org_scope_key,
            "task_id": self.task_id,
            "idempotency_key": self.idempotency_key,
        }


@dataclass(frozen=True)
class LinkOutcome:
    """Result of a linkage attempt."""

    linkage: RuntimeRunLinkage
    action: LinkAction


def _validated_run_id(value: Any, *, source: str) -> str:
    """Fail closed on a runtime run id that is empty or malformed.

    Used both for a value about to be linked and for one read back out of a
    stored linkage, so a tampered extras slot cannot inject a run id that no
    Runtime call could ever have produced.
    """
    candidate = str(value or "").strip()
    if not candidate:
        raise RuntimeRunLinkageError("runtime_run_id is required")
    if not _RUN_ID_PATTERN.fullmatch(candidate):
        raise RuntimeRunLinkageError(f"{source} runtime run id is malformed")
    return candidate


def _decode(raw: Any) -> RuntimeRunLinkage:
    if isinstance(raw, str):
        try:
            raw = json.loads(raw)
        except (TypeError, ValueError) as exc:
            raise RuntimeRunLinkageError("stored runtime run linkage is not valid JSON") from exc
    if not isinstance(raw, Mapping):
        raise RuntimeRunLinkageError("stored runtime run linkage is not a mapping")
    values: dict[str, str] = {}
    for field_name in ("runtime_run_id", "org_scope_key", "task_id", "idempotency_key"):
        value = str(raw.get(field_name) or "").strip()
        if not value:
            raise RuntimeRunLinkageError(f"stored runtime run linkage has no {field_name}")
        values[field_name] = value
    values["runtime_run_id"] = _validated_run_id(
        values["runtime_run_id"], source="stored runtime run linkage"
    )
    return RuntimeRunLinkage(**values)


def read_runtime_run_linkage(
    task: Mapping[str, Any] | None,
    *,
    org_scope_key: str,
) -> RuntimeRunLinkage | None:
    """Read the linkage for ``task``, scoped to the caller's trusted organization.

    Returns ``None`` only when no linkage exists. A linkage that exists but
    belongs to another organization, or to another task, is refused.
    """
    if not isinstance(task, Mapping):
        raise RuntimeRunLinkageError("no server-loaded task row supplied")
    trusted_org = str(org_scope_key or "").strip()
    if not trusted_org:
        raise RuntimeRunLinkageError("no trusted organization scope supplied")

    raw = task.get(LINKAGE_TASK_KEY)
    if raw is None:
        return None

    linkage = _decode(raw)
    if linkage.org_scope_key != trusted_org:
        raise RuntimeRunLinkageError("runtime run linkage belongs to another organization")
    task_id = str(task.get("id") or "").strip()
    if not task_id:
        raise RuntimeRunLinkageError("task row has no id")
    if linkage.task_id != task_id:
        raise RuntimeRunLinkageError("runtime run linkage belongs to another task")
    return linkage


def read_stored_linkage(task: Mapping[str, Any] | None) -> RuntimeRunLinkage | None:
    """Decode the stored linkage **without** an organization check.

    Advisory only, and deliberately so. Every authoritative Task <-> Runtime path
    goes through :func:`read_linked_runtime_run`, which resolves the organization
    from the trusted context and refuses a foreign linkage. This exists for a
    caller that must answer a question about a task it cannot yet scope — a
    scheduler asking whether an attempt has already been handed to the Runtime —
    where the worst a forged value can do is make the caller *defer* work, never
    authorize it. Nothing here may feed a creation, cancellation or projection
    decision (AG-G2-AUTO-021).
    """
    if not isinstance(task, Mapping):
        raise RuntimeRunLinkageError("no server-loaded task row supplied")
    raw = task.get(LINKAGE_TASK_KEY)
    if raw is None:
        return None
    return _decode(raw)


def read_linked_runtime_run(
    task: Mapping[str, Any] | None,
    *,
    context: TaskRuntimeContext,
) -> RuntimeRunLinkage | None:
    """The single organization-consistency gate for every Task <-> Runtime path.

    AG-G2-AUTO-009. Read, status projection, cancel, retry/re-attach and event
    bridging all obtain the linkage through this function, so the trusted
    organization is checked in exactly one place instead of once per caller.

    The context is the *only* source of the organization. A linkage that exists
    but belongs to another organization, or to another task, is refused rather
    than reported as absent, so it can never be adopted by the wrong scope. The
    refusal text stays server-side; callers surface it through their existing
    not-found / refusal semantics and never echo it to a client, so a foreign
    organization's run is never revealed to exist.
    """
    if not isinstance(context, TaskRuntimeContext):
        raise RuntimeRunLinkageError("no trusted task runtime context supplied")
    if not isinstance(task, Mapping):
        raise RuntimeRunLinkageError("no server-loaded task row supplied")

    task_id = str(task.get("id") or "").strip()
    if not task_id:
        raise RuntimeRunLinkageError("task row has no id")
    if task_id != context.task_id:
        raise RuntimeRunLinkageError("task runtime context does not belong to this task")

    return read_runtime_run_linkage(task, org_scope_key=context.org_scope_key)


def link_runtime_run(
    task: Mapping[str, Any] | None,
    *,
    context: TaskRuntimeContext,
    runtime_run_id: str,
    supersede: bool = False,
) -> tuple[dict[str, Any], LinkOutcome]:
    """Attach or reuse the runtime run linkage on an existing task row.

    Returns the updated task dict (to be persisted through the existing task
    save path) plus what happened. Raises :class:`RuntimeRunLinkageError` rather
    than creating a second Runtime Run for the same trigger.
    """
    if not isinstance(task, Mapping):
        raise RuntimeRunLinkageError("no server-loaded task row supplied")
    if not isinstance(context, TaskRuntimeContext):
        raise RuntimeRunLinkageError("no trusted task runtime context supplied")

    run_id = _validated_run_id(runtime_run_id, source="runtime_run_id")

    # Same gate as every other path: trusted organization + task ownership.
    existing = read_linked_runtime_run(task, context=context)

    if not context.authorized:
        raise RuntimeRunLinkageError("task runtime context is not authorized")

    task_id = context.task_id

    if existing is None:
        action: LinkAction = "attached"
        linkage = RuntimeRunLinkage(
            runtime_run_id=run_id,
            org_scope_key=context.org_scope_key,
            task_id=task_id,
            idempotency_key=context.idempotency_key,
        )
    elif existing.idempotency_key == context.idempotency_key:
        if existing.runtime_run_id != run_id:
            raise RuntimeRunLinkageError(
                "this trigger is already linked to another runtime run; "
                "reuse the existing run instead of creating a second one"
            )
        action = "reused"
        linkage = existing
    elif supersede:
        action = "superseded"
        linkage = RuntimeRunLinkage(
            runtime_run_id=run_id,
            org_scope_key=context.org_scope_key,
            task_id=task_id,
            idempotency_key=context.idempotency_key,
        )
    else:
        raise RuntimeRunLinkageError(
            "this task is already linked to a runtime run for another attempt; "
            "pass supersede=True to replace it explicitly"
        )

    updated = dict(task)
    updated[LINKAGE_TASK_KEY] = linkage.to_dict()
    return updated, LinkOutcome(linkage=linkage, action=action)
